FROM tomcat:latest
RUN rm -rf /usr/local/tomcat/webapps/* && cp -R /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps
EXPOSE 8080
COPY /webapp/target/*.war /usr/local/tomcat/webapps/ROOT.war
CMD ["catalina.sh", "run"]

--> dockerfile for java application (The target directory is created during the build process. Exactly, When your Jenkins pipeline (or you, locally) runs mvn clean package, Maven compiles the Java code, bundles the frontend, and creates that target/ directory inside the webapp folder. That directory contains the compiled .war artifact)
